# render.yaml
services:
  - type: web
    name: image-hub
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --workers 4 'app:app'"
    disk:
      name: image-hub-data
      mountPath: /var/data/image_hub_data
      sizeGB: 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
