# render.yaml
services:
  - type: web
    name: image-hub
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --workers 4 'app:app'"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
    disks:
      - name: image-hub-data
        mountPath: /var/data/image_hub_data
        sizeGB: 1
